"""add pick column

Revision ID: a3eaccf81518
Revises: c2f00dca76c7
Create Date: 2023-07-30 14:42:25.073660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3eaccf81518'
down_revision = 'c2f00dca76c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ourpicks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pick', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ourpicks', schema=None) as batch_op:
        batch_op.drop_column('pick')

    # ### end Alembic commands ###
