"""empty message

Revision ID: c2f00dca76c7
Revises: 
Create Date: 2023-07-30 13:24:41.183093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2f00dca76c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cocktails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('preptime', sa.String(), nullable=True),
    sa.Column('waittime', sa.String(), nullable=True),
    sa.Column('cooktime', sa.String(), nullable=True),
    sa.Column('totaltime', sa.String(), nullable=True),
    sa.Column('servings', sa.Integer(), nullable=True),
    sa.Column('comments', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('instructions', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('ingredients', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('drink_type', sa.String(), nullable=True),
    sa.Column('alcohol_type', sa.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cocktails'))
    )
    op.create_table('ourpicks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('preptime', sa.String(), nullable=True),
    sa.Column('waittime', sa.String(), nullable=True),
    sa.Column('cooktime', sa.String(), nullable=True),
    sa.Column('totaltime', sa.String(), nullable=True),
    sa.Column('servings', sa.Integer(), nullable=True),
    sa.Column('comments', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('instructions', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('ingredients', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('cuisine', sa.String(), nullable=True),
    sa.Column('course', sa.String(), nullable=True),
    sa.Column('vegetarian', sa.Boolean(), nullable=True),
    sa.Column('meat', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('contains', sa.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ourpicks'))
    )
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('preptime', sa.String(), nullable=True),
    sa.Column('waittime', sa.String(), nullable=True),
    sa.Column('cooktime', sa.String(), nullable=True),
    sa.Column('totaltime', sa.String(), nullable=True),
    sa.Column('servings', sa.Integer(), nullable=True),
    sa.Column('comments', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('instructions', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('ingredients', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('cuisine', sa.String(), nullable=True),
    sa.Column('course', sa.String(), nullable=True),
    sa.Column('vegetarian', sa.Boolean(), nullable=True),
    sa.Column('meat', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('contains', sa.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipes'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('_password_hash', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('cocktail_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cocktail_id'], ['cocktails.id'], name=op.f('fk_favorites_cocktail_id_cocktails')),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name=op.f('fk_favorites_recipe_id_recipes')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_favorites_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_favorites'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    op.drop_table('users')
    op.drop_table('recipes')
    op.drop_table('ourpicks')
    op.drop_table('cocktails')
    # ### end Alembic commands ###
